preset: recommended
risky: true
use-tabs: false
tab-width: 4
finder:
    exclude:
        - vendor
        - stubs
    name: "*.php"
    not-name:
        - "*.yml"
        - "*.stub"
        - "*.md"
