preset: recommended
risky: true
use-tabs: true
tab-width: 4
disabled:
    - indentation
finder:
    exclude:
        - vendor
        - stubs
    name: "*.php"
    not-name:
        - "*.yml"
        - "*.stub"
        - "*.md"
